src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

[JENKINS-26606](https://issues.jenkins-ci.org/browse/JENKINS-26606)
Simple fix to get `MimeMessageBuilder` to include commas  as a valid delimiter when tokenizing the recipient list.
@reviewbybees

[FIXED JENKINS-26606] Recipient list tokenizer not including comma delim

---

pom.xml
src/main/java/hudson/cli/MailCommand.java
src/main/java/hudson/tasks/MailSender.java
src/main/java/hudson/tasks/Mailer.java
src/main/java/jenkins/plugins/mailer/tasks/MailAddressFilter.java
src/test/java/hudson/tasks/MailAddressResolverTest.java
src/test/java/jenkins/plugins/mailer/tasks/MailAddressFilterTest.java

The change could only require 1.580.1 but then I wouldn't get to use the wonderful ```Jenkins.getActiveInstance()```
@reviewbybees

Making it buildable with jdk8 and fixed findbugs issues

---

src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

See [JENKINS-32301](https://issues.jenkins-ci.org/browse/JENKINS-32301)
Some additional refactoring of `MimeMessageBuilderTest` included.
@reviewbybees

[JENKINS-32301] Support more than one Reply-To Address

---

pom.xml
src/main/java/hudson/tasks/MailSender.java

Updates mailer to use the `DisplayURLProvider` so that Blue Ocean can send its own URLs instead of classic.
Depends on #28 so that we can depend on a recent Jenkins snapshot that contains `URLFactory`
Waiting on https://issues.jenkins-ci.org/browse/HOSTING-179
@jenkinsci/code-reviewers

Update mailer to use new display-url-api for user facing page links

---

src/main/java/hudson/tasks/Mailer.java

required for configuration-as-code
Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>

Mailer: fix missing getter for smtpHost property

---

pom.xml
src/main/java/hudson/tasks/Mailer.java
src/test/java/hudson/tasks/MailerTest.java

See [JENKINS-37812](https://issues.jenkins-ci.org/browse/JENKINS-37812)
Class [`Mailer`](https://github.com/jenkinsci/mailer-plugin/blob/master/src/main/java/hudson/tasks/Mailer.java#L96) is implementing the interface `SimpleBuildStep`. Since the workspace is only used to format the email sent, it's not entirely needed to fail if the workspace is not retrieved. With this PR the email notifying that the build failed will be sent even if the agent goes offline.
Added a test that checks that the email is sent and fails with the precious code.
@reviewbybees @alecharp

[JENKINS-37812] No notification re. failed job if agent goes offline during the build

---

README.adoc
README.md

subj. I moved the docs, but I did not change the content except using a new JavaMail link: https://javaee.github.io/javamail/

Move documentation from Wiki to GitHub

---

src/main/java/hudson/tasks/Mailer.java
src/main/resources/hudson/tasks/Mailer/global.jelly

`doSendTestMail` uses the `useSmtpAuth` JSON attribute to send a test mail using authentication.
As the case of the parameter has been changed from `useSMTPAuth` to `useSmtpAuth` in #44 the corresponding JSON needs to be updated.
Withouth this change, sending test mails using SMTP authentication is not possible, as the condition in line 598 is always false.
```JAVA
if (!useSmtpAuth) {
smtpAuthUserName = null;
smtpAuthPasswordSecret = null;
}
```

[JENKINS-58768] Fix send test mail after adding JCasC compatibility

---

src/main/java/hudson/tasks/MailSender.java

Otherwise separator line will stick to the build URL, rendering to unusable link

[JENKINS-39976] Add line break before separator line even if there are no changesets found

---

src/main/java/hudson/tasks/Mailer.java

- The deprecated member variables `smtpAuthUsername` and `smtpAuthPassword` are only filled in case of an upgrade
- Use the proper getter methods for the username and the password secret

[JENKINS-59483] Fix SMTP authentication Job emails

---

src/main/java/hudson/tasks/MailSender.java

Fixes [JENKINS-58727](https://issues.jenkins-ci.org/browse/JENKINS-58727)
This PR restricts the previously misleading warning
> No mail will be sent out, as 'XXX' does not have a result yet. Please make sure you set a proper result in case of pipeline/build scripts.
to situations where no build result was set at the point of this plugin's execution.

[JENKINS-58727] Warn only if no build result exists

---

src/main/java/hudson/tasks/Mailer.java

See:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1309
Example yaml:
```yaml
jenkins:
securityRealm:
local:
allowsSignup: true
enableCaptcha: false
users:
- description: "I am admin"
id: "admin"
name: "Admin"
properties:
- mailer:
emailAddress: "admin3@example.com"
```

JCasC compatibility for user property

---

src/main/java/hudson/tasks/Mailer.java
src/main/resources/hudson/tasks/Mailer/global.jelly
src/main/resources/hudson/tasks/Mailer/global_es.properties

The [reported bug](https://issues.jenkins-ci.org/browse/JENKINS-2206) asked about a problem I also found while trying to configure Jenkins mailer with office365 smtp, which happens to use TLS only (no SSL). The workaround in the bug comments works but being able to set up config from the form (instead of the startup JAVA params) could be useful and more manageable.
What I changed here to achieve it is the folowing:
- new option in jelly config form to enable/disable TLS usage
- new attribute to handle boolean option
- new javaMail properties used when TLS option is selected
- validation of default TLS port 587 if no port is defined by user
- testEmail method modified to use new parameter while testing TLS configurations
- Spanish translation for new form field added

[JENKINS-2206] - Support connecting to mail servers via TLS

---

README.adoc
src/main/java/hudson/tasks/Mailer.java
src/test/java/jenkins/plugins/mailer/MailerJCasCCompatibilityTest.java
src/test/resources/jenkins/plugins/mailer/configuration-as-code.yaml

I installed v1.31 of this plugin and found that the `useTls` option didn't appear in the CasC reference documentation, nor did it accept a YAML file with the option.
Adding a getter for the property seems to make this work.
Follows on from the work done in #76

Fix CasC support for useTls

---

src/main/java/hudson/tasks/Mailer.java
src/main/java/hudson/tasks/SMTPAuthentication.java
src/main/resources/hudson/tasks/Mailer/global.jelly
src/test/java/hudson/tasks/MailerTest.java

Adding trimming to the following attributes:
* SMTP server (smtpHost)
* User Name (authentication/user)
* SMTP Port (smtpHost)
* Reply-To Address (replyToAddress)
* Charset (charset)
Also standardized the reference to Util.fixEmptyAndTrim
Signed-off-by: Darin Pope <darin@planetpope.com>

Hacktoberfest: Trim white space

---

src/main/java/hudson/tasks/MailSender.java
src/main/resources/jenkins/plugins/mailer/tasks/i18n/Messages.properties

When attempting to email a user with a locked, disabled, or otherwise unauthorized account, different types of AuthenticationException were not caught which would cause the mail to fail.
https://issues.jenkins.io/browse/JENKINS-64629
Related to error message updates in https://github.com/jenkinsci/ldap-plugin/pull/74 which helped surface the problem.
@jeffret-b @basil @jglick @l3ender

[JENKINS-64629] Fix uncaught exception for unauthorized users

---

src/main/resources/hudson/tasks/Mailer/config_it.properties
src/main/resources/hudson/tasks/Mailer/global_it.properties
src/main/resources/hudson/tasks/Mailer/help-authentication_it.html
src/main/resources/hudson/tasks/Mailer/help-defaultSuffix_it.html
src/main/resources/hudson/tasks/Mailer/help-sendToIndividuals_it.html
src/main/resources/hudson/tasks/Mailer/help-smtpPort_it.html
src/main/resources/hudson/tasks/Mailer/help-smtpServer_it.html
src/main/resources/hudson/tasks/Mailer/help-useSsl_it.html
src/main/resources/hudson/tasks/Mailer/help_it.html
src/main/resources/hudson/tasks/SMTPAuthentication/config_it.properties
src/main/resources/jenkins/plugins/mailer/tasks/i18n/Messages_it.properties

This PR updates the Italian translation of this plugin.
Note that I have redone the translation from scratch; for this reason, the copyright notice in `src/main/resources/hudson/tasks/Mailer/UserProperty/config_it.properties` has been changed to include only my name.

i18n: update the Italian translation

---

src/main/resources/hudson/tasks/Mailer/UserProperty/config_fr.properties

I saw that when checking the french version of user configuration (for https://github.com/jenkinsci/jenkins/pull/5009). The word "Indian" may be offensive, I am not sure but I prefer to be on fence and use a safe name.
I checked, in english it's not the same name (it's joe chin, no idea if it's ok or not).

[terminology] Removing indian word in French email example.

---

src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/hudson/tasks/MailSenderTest.java

Remove usages of Guava

---

pom.xml
src/test/java/hudson/tasks/MailAddressResolverTest.java
src/test/java/hudson/tasks/MailSenderTest.java
src/test/java/jenkins/plugins/mailer/tasks/MailAddressFilterTest.java

Adapts to jenkinsci/plugin-pom#442.
CC @alecharp

Remove PowerMock

---

src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

Java 8 includes a built-in Base64 decoder, so there is no reason to depend on a third-party library. Using the built-in Java Platform functionality simplifies maintenance.
CC @alecharp

Drop dependency on Commons Codec

---

README.adoc
src/main/java/hudson/tasks/Mailer.java
src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/hudson/tasks/MailerTest.java
src/test/java/jenkins/plugins/mailer/MailerJCasCCompatibilityTest.java

On Mailer class:
+ Solved a TODO left in a previous commit on the SSL connection setup to SMTP server. So, `socketFactory` property was replaced by `mail.smtp.ssl.enable`. Additionally, added another property, `mail.smtp.ssl.checkserveridentity` in the SSL set-up, to enforce server identity check to avoid MITM attacks.
+ Also, addressed older TODOs about `Jenkins.getInstance` using the method recommended by Jenkins [docs](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getInstanceOrNull--) (`getInstanceOrNull`).
+ A couple of `@deprecated` annotations were on top of javaDoc blocks, hence they were being ignored. Moved them on top of the declaration and checked that javaDoc worked as expected.
+ Addressed a TODO about a try-with-resources for a BulkChange instance that was not …

Resolve Mailer TODOs & warnings, fixing port data in README 

---

pom.xml
src/test/java/hudson/tasks/MailerTest.java

Downstream of #142 and jenkinsci/jenkins#6165. Bumps the baseline to one containing jenkinsci/jenkins#6165, thus using the detached JavaMail plugin, but does not upgrade to Jakarta Mail.

Use detached JavaMail plugin

---

pom.xml
src/main/java/hudson/tasks/Mailer.java
src/main/resources/jenkins/plugins/mailer/tasks/i18n/Messages.properties
src/test/java/hudson/tasks/MailerTest.java

Additionally if running in FIPS use an error in the form validation and do not support auth without SSL or TLS.
This is handled when we attempt to send as the config is part of the global configuration and could leave the config in an non determinate state
```[tasklist]
```

Warn when using insecure auth

---

src/main/java/hudson/tasks/SMTPAuthentication.java

While I was reading though code notice some magic numbers on FIPS password length, nothing really stopping FIPS standards to change password length in future to increase security posture. This will require several modifications in code which is error prone. Replacing magic numbers with `MIN_PASSWORD_LENGTH` constant.
Done testing with `mvn clean insatll`
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Running tests for org.jenkins-ci.plugins:mailer:999999-SNAPSHOT
[INFO] Running hudson.tasks.MailAddressResolverTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.094 s -- in hudson.tasks.MailAddressResolverTest
[INFO] Running hudson.tasks.MailSenderTest
[INFO] Tests …
```

Replacing magic numbers with constant

---

src/test/java/hudson/tasks/MailAddressResolverTest.java
src/test/java/hudson/tasks/MailSenderTest.java
src/test/java/hudson/tasks/MailerTest.java
src/test/java/jenkins/plugins/mailer/FipsModeTest.java
src/test/java/jenkins/plugins/mailer/MailerJCasCCompatibilityTest.java
src/test/java/jenkins/plugins/mailer/tasks/MailAddressFilterTest.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations
* Migrate assertions
* Cleanup assertions
* Minor cleanup
* Remove public visibility of test classes and methods
There is once exception in `jenkins.plugins.mailer.FipsModeTest` which was not migrated as it uses `RealJenkinsRule` for which there is no JUnit4 equivalent yet.
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewd.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

src/main/java/hudson/tasks/MailSender.java

getCulpritsOfEmailList() may return null but addRecipients() must not get null values

getCulpritsOfEmailList() may return null

---

src/main/java/hudson/tasks/Mailer.java
src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java

No need to use a third-party library when this functionality is available in the Java Platform.

Migrate from Commons Lang to native Java Platform functionality
