src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

Provide the correct charset to the mime message body.
Tests included.

[JENKINS-26758] Fix MimeMessageBuilder charset

---

pom.xml
src/main/java/hudson/tasks/Mailer.java
src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
src/test/java/hudson/tasks/MailerTest.java

[JENKINS-33266] Upgrade to new Parent POM

---

src/test/java/hudson/tasks/MailerTest.java

See [JENKINS-33291](https://issues.jenkins-ci.org/browse/JENKINS-33291):
Test post build step options:
* Notify in every unstable build.
* Notify "culprits".
Includes some refactoring of the existing tests.
Edited after merging master: was downstream of https://github.com/jenkinsci/mailer-plugin/pull/24 (will rebase once upstream is merged, at this point only https://github.com/jenkinsci/mailer-plugin/commit/73c521ca2f40b0d9d7bf786a39bf4d5dddec915c is significant).
@reviewbybees

[JENKINS-33291] Additional Tests

---

pom.xml
src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java

See [JENKINS-34324](https://issues.jenkins-ci.org/browse/JENKINS-34324)
@reviewbybees

[JENKINS-34324] Fix PCT against 2.0-rc-1

---

pom.xml

[JENKINS-39999](https://issues.jenkins-ci.org/browse/JENKINS-39999)
@reviewbybees @andresrc

[JENKINS-39999] Add plugin description to POM.

---

src/main/java/hudson/tasks/MailSender.java
src/test/java/hudson/tasks/MailerTest.java

[JENKINS-41881](https://issues.jenkins-ci.org/browse/JENKINS-41881)
Automated test that failed before the fix and passes after it.
@reviewbybees @i386 @jglick

[JENKINS-41881] Automated test to cover fix for JENKINS-40224

---

pom.xml

[JENKINS-41882](https://issues.jenkins-ci.org/browse/JENKINS-41882)
@reviewbybees @jglick

[JENKINS-41882] Fix PCT for 2.32.2

---

.dependabot/config.yml

Like #55 , but in a right way. Free 🤖 labor

Enable Dependabot for the repository

---

src/main/java/hudson/tasks/MailSender.java

(Re-add this commit that was originally added as
11142e5f43e55d5bb0f5dd2c8297e737cf122307)

[JENKINS-25089] Add Auto-Submitted header to emails (RFC 3834)

---

pom.xml
src/test/java/jenkins/plugins/mailer/MailerJCasCCompatibilityTest.java

https://github.com/jenkinsci/configuration-as-code-plugin/pull/1049

fix space in expected log

---

src/main/java/hudson/tasks/Mailer.java
src/test/java/hudson/tasks/MailerTest.java

Correcting a mistake from https://github.com/jenkinsci/mailer-plugin/commit/f225469e7ca0982de6cf1a16b4345dbe2cb5d9ad

[JENKINS-59430] Do not reset auth to current value unconditionally

---

README.adoc

Change text in the changelog badge to be more explicit

---

Jenkinsfile

It never updates and stops people from being able to update the baseline -.-

Don't use recommended configurations

---

src/main/java/hudson/tasks/MailSender.java
src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java

NOTE: The larger deletion in MailSender.java was due to spotbugs failing. Once the resulting code was in place, spotbugs was successful.
@alecharp @oleg-nenashev

Cleanup getInstance() references

---

pom.xml

move pipeline job back to test scope

---

README.adoc

This pull request fixes a small typo in the readme.

Fix typo about e-mail for every unstable build

---

pom.xml

Move to 2.361.x

---

pom.xml

Backporting part of #182 which seems to be necessary for PCT: https://github.com/jenkinsci/bom/pull/1543#issuecomment-1301037415

Update BOM in 435.x branch

---

.github/workflows/security-scan.yaml

This enables the security scan workflow, based on https://www.jenkins.io/doc/developer/security/scan/ and following the template in https://github.com/jenkinsci/.github/blob/master/workflow-templates/jenkins-security-scan.yaml.
None.
```[tasklist]
```

Creates security scan workflow

---

src/test/java/hudson/tasks/MailAddressResolverTest.java
src/test/java/hudson/tasks/MailSenderTest.java
src/test/java/hudson/tasks/MailerTest.java
src/test/java/jenkins/plugins/mailer/FipsModeTest.java
src/test/java/jenkins/plugins/mailer/tasks/MailAddressFilterTest.java
src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5
